### ISSUE TITLE
Winning rule about the diagonal line

### ISSUE THREAD

**Issue by jouae** [jserv/ttt#10]
![Screenshot from 2024-01-26 20-49-27](https://github.com/jserv/ttt/assets/51120603/77ec59d7-34c0-4082-9ac1-c861a9c03c7c)

Is it legal that the off-diagonal line scores in 4x4 board like the figure above?

Since the rule about diagonal line is not clear, in general only diagonal (A1-B2-C3-D4 and A4-B3-C2-D1) can get the score not the "off-diagonal"

**Comment by jserv** [comment]
> Is it legal that the off-diagonal line scores in 4x4 board like the figure above?

I believe it is indeed permissible.

> Since the rule about diagonal line is not clear, in general only diagonal (A1-B2-C3-D4 and A4-B3-C2-D1) can get the score not the "off-diagonal"

Please consider submitting a pull request to help clarify the rules in both the documentation and the source code.

**Comment by jserv** [comment]
Close in favor of #11 .
