### ISSUE TITLE
Winning rule is not correct about 4x4 board

### ISSUE THREAD

**Issue by jouae** [jserv/ttt#11]
![image](https://github.com/jserv/ttt/assets/51120603/4a44f1ba-c962-49e9-b247-8a5cd5286809)

The winning rule is not correct for the 4x4 board

**Comment by jserv** [comment]
@ndsl7109256, can you check?

**Comment by ndsl7109256** [comment]
Hi @jouae. Thanks for your issues. Perhaps you have misunderstood the winning rule.
From the [post](https://www.facebook.com/groups/system.software2024/posts/1537722963672263/?__cft__[0]=AZVtgEB5_CiX7lv-98Ifh-nYslm2ykQxyLRoTBZuUSH41bfJ0beHhlQNJxUWkewuU9PT5XQB2-vN2qXF6XJOnRNB2NwgDUp_0tGQqx1_ljkiHvUwWJmsaHcmipVb6xnkpLVzyyN8CW86qvvUld2i9UWE&__tn__=%2CO%2CP-R), despite the board is expanded to NxN, we still use the criteria of the earliest continuous 3 O's or X's in a row, column, or diagonal to determine the winner.

**Comment by jouae** [comment]
@ndsl7109256 Thanks! It's my mistake.

**Comment by jouae** [comment]
@jserv this issue can be close thanks !
