### ISSUE TITLE
Clarification and Details Needed on Project Architecture

### ISSUE THREAD

**Issue by scc-tw** [jserv/ttt#6]
I came across a post in the [System Software 2024 Facebook group](https://www.facebook.com/groups/system.software2024/posts/1537722963672263/) discussing this project, but there are several aspects that require further clarification and details:

1. **Linux Char Device Driver Location:** The post mentions that this project includes a Linux character device driver. Could you please specify where exactly in the repository the driver code would be located?

2. **User Space-Kernel Space API Design:** What is the current design of the API that facilitates communication between the user space and kernel space? It would be helpful to have a detailed explanation or documentation about this.

3. **Embedding Machine Learning Model in Kernel:** The post also indicates that a machine-learning model is embedded into the kernel. Could you provide guidance or existing design principles that have been followed for embedding such a model? Additionally, it would be beneficial to understand the expected behavior and limitations of this integration.

Understanding these elements is crucial for comprehensively grasping the architecture of this project. Any detailed information or documentation regarding these aspects would be greatly appreciated.

**Comment by scc-tw** [comment]
I understand that the third issue might be more relevant for a future roadmap. However, we could discuss its scope now to better define our plans going forward.

**Comment by jserv** [comment]
Did you review the repository's descriptions? They are not connected to a Linux kernel module, but rather pertain to a userspace program.
